config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#index', as: :index
  post '/login' => 'sessions#create', as: :session_create
  get '/show' => 'sessions#show'
  delete '/logout' => 'sessions#destroy'

  get 'show/:id/index' => 'users#index', as: :edit_user
  post 'show/:id/index' => 'users#edit', as: :user
  post 'show/new' => 'users#create', as: :users
  get 'show/new' => 'users#new'
  get 'show/show' => 'users#show'



  get 'show/:id' => 'employees#show', as: :employee
  get '/view' => 'employees#view', as: :view

  resources :employees do
    collection do
      post :mark_checkin
      post :mark_checkout
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
  validates_presence_of :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
  validates_presence_of :user
  has_many :records, dependent: :destroy
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :employee
end

app/models/user.rb
class User < ApplicationRecord
  has_one :employee, dependent: :destroy
  has_one :admin, dependent: :destroy
  accepts_nested_attributes_for :employee, update_only: true
  has_secure_password
  # Role = 1 , admin
  # Role = 2 , employee
  validates :role, presence: true
  validates :role, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 2}

  def allowed_role?(role)
    self.role >= role
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include FormHelper

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
before_action :require_user
before_action :verify_role, except: [:view]

  def view
  end

  def show
      @employee = Employee.find(params[:id])
      @records = @employee.records
  end


  def mark_checkin
    employee = Employee.find(params[:id])
    if Record.where('employee_id = ? and check_in >= ? and check_in < ?', employee.id, Date.current.beginning_of_day, Date.current.beginning_of_day + 1.day).any?
      flash[:check_in] = 'Ya has registrado esta entrada'
      redirect_to '/'
    else
      record = Record.new(employee_id: employee.id, check_in: Time.now)
      if record.save!
        flash[:check_in] = 'Entrada registrada correctamente'
        redirect_to '/'
      else
        flash[:check_in] = 'No se ha podido registrar la entrada'
        redirect_to '/'
      end
    end
  end


  def mark_checkout
    employee = Employee.find(params[:id])
    if Record.where('employee_id = ? and check_in >= ? and check_in < ?', employee.id, Date.current.beginning_of_day, Date.current.beginning_of_day + 1.day).any?
      if Record.where('employee_id = ? and check_out >= ? and check_out < ?', employee.id, Date.current.beginning_of_day, Date.current.beginning_of_day + 1.day).any?
        flash[:check_out] = 'Ya has registrado esta salida'
        redirect_to '/'
      else
        record = Record.where('employee_id = ? and check_in >= ? and check_in < ?', employee.id, Date.current.beginning_of_day, Date.current.beginning_of_day + 1.day)
        if record.update(check_out: Time.now)
          flash[:check_out] = 'Salida registrada correctamente'
          redirect_to '/'
        else
          flash[:check_out] = 'No se ha podido registrar la salida'
          redirect_to '/'
        end
      end
    else
      flash[:check_out] = 'Aún no se ha registrado la entrada el día de hoy'
      redirect_to '/'
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_user, only: [:index, :create]
  before_action :require_user, except: [:index, :create]
  before_action :verify_role, only: [:show]

  def index
  end

  def create
    if user = User.find_by_email(params[:email].downcase)
      if user && user.authenticate(params[:password])
        log_in user
        if current_user.allowed_role?(2)
          redirect_to '/show'
        else
          redirect_to view_path
        end
      else
        redirect_to '/'
        flash[:invalid_login] = "Tus credenciales son incorrectas"
      end
    else
      redirect_to '/'
      flash[:invalid_login] = "Tus credenciales son incorrectas"
    end
  end

  def show
    @user = User.where("role = '1'").order(:id)
    @employees = @user.map do |u| u.employee end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :require_user
before_action :verify_role

  def index
    @employee = Employee.find(params[:id])
    @user = User.find(@employee.user_id)
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(new_user_params)
    user.id = User.maximum('id') + 1
    user.employee.id = Employee.maximum('id') + 1

    if user.save!
      redirect_to index_path
    else
      redirect_to 'show/new'
    end

  end

  def edit
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to '/'
    else
      redirect_to edit_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:id, :email, employee_attributes: [:id, :first_name, :last_name])
  end

  def new_user_params
    params.require(:user).permit(:email, :password, :role, employee_attributes: [:first_name, :last_name])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/form_helper.rb
module FormHelper

  def setup_user(user)
    user.employee ||= Employee.new
    user
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/' unless current_user
  end

  def logged_user
    if !current_user.nil?
      if current_user.allowed_role?(2)
        redirect_to '/show'
      else
        redirect_to view_path
      end
    end
  end

  def verify_role
    redirect_to '/' unless current_user.allowed_role?(2)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employees/show.html.haml
.employees_show
 .container
  .row.user
   .col-md-8.col-xs-8
    =link_to edit_user_path(:id => @employee.id) do
     %h3
      %span.fas.fa-user-edit
       %span.hover_text Editar Empleado
      %span= "&nbsp; &nbsp;".html_safe + @employee.first_name+' '+@employee.last_name
   .col-md-4.col-xs-4
    =link_to index_path do
     %span.fas.fa-arrow-alt-circle-left
      %span.hover_text Regresar
  .row.top
   .col-md-4.col-xs-4
    %p Fecha
   .col-md-4.col-xs-4
    %p Entrada
   .col-md-4.col-xs-4
    %p Salida
  - @employee.records.each do |r|
   .row.emp
    .col-md-4.col-xs-4
     =r.check_in.beginning_of_day.strftime("%Y - %m - %d").to_s
    .col-md-4.col-xs-4
     =r.check_in.to_formatted_s(:time)
    .col-md-4.col-xs-4
     - if r.check_out
      =r.check_out.to_formatted_s(:time)

app/views/employees/view.html.haml
.employees_view
 .container
  .row.top
   .col-md-4.col-xs-4
    %p Fecha
   .col-md-4.col-xs-4
    %p Entrada
   .col-md-4.col-xs-4
    %p Salida
  - current_user.employee.records.each do |r|
   .row.emp
    .col-md-4.col-xs-4
     =r.check_in.beginning_of_day.strftime("%Y - %m - %d").to_s
    .col-md-4.col-xs-4
     =r.check_in.to_formatted_s(:time)
    .col-md-4.col-xs-4
     - if r.check_out
      =r.check_out.to_formatted_s(:time)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AdminApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :integrity => "sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/", :rel => "stylesheet"}/
    = stylesheet_link_tag href = "https://fonts.googleapis.com/css?family=Nunito|Dosis|Noto+Serif|Open+Sans+Condensed:300|Slabo+27px"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      .container
        -if current_user
          .row
            .col-md-8
              .time-container
                %h2
                  %span.fas.fa-calendar-day= "&nbsp; &nbsp;".html_safe + Time.now.strftime("%Y - %m - %d")
            .col-md-4
              %p= current_user.email
              %p= link_to 'Salir', logout_path, method: 'delete', class: 'logout'
    = yield

app/views/users/index.html.haml
.users_index
 .container
  .form
   =link_to index_path do
    %span.fas.fa-arrow-alt-circle-left
   =form_for @user, :method => :post do |f|
    = f.email_field :email
    %br
    = f.fields_for :employee do |e|
     = e.text_field :first_name
     %br
     = e.text_field :last_name
    %br
    = f.submit "Actualizar"

app/views/users/new.html.haml
.users_new
 .container
  .form
   =link_to index_path do
    %span.fas.fa-arrow-alt-circle-left
   =form_for setup_user(@user), :method => :post do |f|
    =f.email_field :email, placeholder: "Email"
    %br
    =f.password_field :password, placeholder: "Contraseña"
    %br
    = f.fields_for :employee do |e|
     = e.text_field :first_name, placeholder: "Nombre(s)"
     %br
     = e.text_field :last_name, placeholder: "Apellidos"
    %br
    = f.hidden_field :role, :value => 1
    = f.submit "Crear"